name: Lua docs generator
description: Generates markdown documentation from in-line Lua comments
branding:
  icon: package
  color: green
inputs:
  path:
    description: Path containing files to parse.
    required: true
runs:
  using: docker
  image: Dockerfile
  entrypoint: /usr/local/bin/parse
  args:
    - -o ${{ inputs.path }}
